name = "prasanth-portfolio"
compatibility_date = "2024-02-02"
usage_model = 'bundled'
workers_dev = false

[site]
  bucket = "./"
  entry-point = "index.html"

[build]
  command = "npm install --force && npm run build"

[build.upload]
  dir = "./dist/prasanth-arumugam-portfolio"
